package com.closetos.app.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.closetos.app.data.model.Garment
import com.closetos.app.data.repository.ClosetRepository
import com.closetos.app.data.repository.NotificationCenter
import com.closetos.app.showToast
import com.closetos.app.ui.components.ElegantButton
import com.closetos.app.ui.components.GlassmorphicCard
import com.closetos.app.ui.components.SectionHeader
import com.closetos.app.ui.theme.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ResaleScreen() {
    val allGarments by ClosetRepository.garments.collectAsState()

    // Identify underworn garments (Cost-Per-Wear > 20 and worn less than 3 times)
    val underwornGarments = remember(allGarments) {
        allGarments.filter { g ->
            g.wearCount < 3 && g.price > 40.0
        }.sortedByDescending { it.costPerWear }
    }

    var selectedGarmentForResale by remember { mutableStateOf<Garment?>(null) }
    var resalePriceVal by remember { mutableStateOf("") }
    var selectedResalePlatform by remember { mutableStateOf("Vinted") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(ObsidianBg)
            .padding(16.dp)
    ) {
        SectionHeader(
            title = "Resale Hook",
            subtitle = "Offload items you don't wear. Auto-list items on Vinted & Poshmark."
        )

        if (underwornGarments.isEmpty()) {
            Box(
                modifier = Modifier.weight(1f).fillMaxWidth(),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = "No underworn high-CPW items found. Keep wearing your clothes!",
                    fontFamily = OutfitFont,
                    color = TextMuted
                )
            }
        } else {
            LazyColumn(
                modifier = Modifier.weight(1f).fillMaxWidth(),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                items(underwornGarments) { garment ->
                    UnderwornItemRow(
                        garment = garment,
                        onListClick = {
                            selectedGarmentForResale = garment
                            resalePriceVal = (garment.price * 0.65).toInt().toString() // Default 65% of retail price
                        }
                    )
                }
            }
        }
    }

    // LISTING MODAL DIALOG
    selectedGarmentForResale?.let { garment ->
        AlertDialog(
            onDismissRequest = { selectedGarmentForResale = null },
            containerColor = CharcoalSurface,
            title = {
                Text(
                    text = "Compose Resale Listing",
                    fontFamily = PlayfairFont,
                    color = AccentGold
                )
            },
            text = {
                Column(
                    verticalArrangement = Arrangement.spacedBy(12.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text(
                        text = "ClosetOS compiled product photos (matte cutout) and description keys to publish on retail marketplaces.",
                        fontFamily = OutfitFont,
                        fontSize = 12.sp,
                        color = TextMuted
                    )

                    // Autogenerated Florence-2 text preview
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(RoundedCornerShape(8.dp))
                            .background(GlassOverlay)
                            .border(0.5.dp, GlassBorder, RoundedCornerShape(8.dp))
                            .padding(12.dp)
                    ) {
                        Text(
                            text = "Florence-2: Excellent condition ${garment.colorName} ${garment.subcategory} by ${garment.brand}. Material: ${garment.material}, Fit: ${garment.fit}. Retailed at $${garment.price}. Worn only ${garment.wearCount} times.",
                            fontFamily = OutfitFont,
                            fontSize = 12.sp,
                            color = TextLight,
                            lineHeight = 16.sp
                        )
                    }

                    // Price suggestion
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        OutlinedTextField(
                            value = resalePriceVal,
                            onValueChange = { resalePriceVal = it },
                            label = { Text("Resale Price ($)", color = TextMuted) },
                            singleLine = true,
                            colors = OutlinedTextFieldDefaults.colors(
                                focusedTextColor = TextLight, focusedBorderColor = AccentGold, unfocusedBorderColor = GlassBorder
                            ),
                            modifier = Modifier.weight(1f)
                        )
                        Text(
                            text = "Retail: $${garment.price}",
                            fontFamily = OutfitFont,
                            fontSize = 12.sp,
                            color = TextMuted
                        )
                    }

                    // Platform select chips
                    Text(
                        text = "Target Marketplace Platform",
                        fontFamily = OutfitFont,
                        fontWeight = FontWeight.SemiBold,
                        fontSize = 13.sp,
                        color = TextLight
                    )
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        listOf("Vinted", "Poshmark", "eBay").forEach { platform ->
                            val isSel = platform == selectedResalePlatform
                            Box(
                                modifier = Modifier
                                    .clip(RoundedCornerShape(8.dp))
                                    .background(if (isSel) AccentGold else GlassOverlay)
                                    .clickable { selectedResalePlatform = platform }
                                    .padding(horizontal = 12.dp, vertical = 6.dp)
                            ) {
                                Text(
                                    text = platform,
                                    fontFamily = OutfitFont,
                                    fontSize = 12.sp,
                                    fontWeight = if (isSel) FontWeight.Bold else FontWeight.Normal,
                                    color = if (isSel) ObsidianBg else TextLight
                                )
                            }
                        }
                    }
                }
            },
            dismissButton = {
                ElegantButton(
                    text = "Cancel",
                    isSecondary = true,
                    onClick = { selectedGarmentForResale = null }
                )
            },
            confirmButton = {
                ElegantButton(
                    text = "Publish List API",
                    onClick = {
                        ClosetRepository.sellGarment(garment.id)
                        showToast("Listing published on $selectedResalePlatform API! Synced in Wardrobe.")
                        selectedGarmentForResale = null
                    }
                )
            }
        )
    }
}

@Composable
fun UnderwornItemRow(garment: Garment, onListClick: () -> Unit) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(16.dp))
            .background(GlassOverlay)
            .border(0.5.dp, GlassBorder, RoundedCornerShape(16.dp))
            .padding(16.dp)
    ) {
        Row(
            verticalAlignment = Alignment.CenterVertically,
            modifier = Modifier.fillMaxWidth()
        ) {
            Box(
                modifier = Modifier
                    .size(50.dp)
                    .clip(RoundedCornerShape(8.dp))
                    .background(Color(0xFF232329)),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    imageVector = when(garment.category) {
                        "Top" -> Icons.Default.Checkroom
                        "Bottom" -> Icons.Default.Accessibility
                        else -> Icons.Default.Checkroom
                    },
                    contentDescription = null,
                    tint = AccentGold
                )
            }

            Spacer(modifier = Modifier.width(16.dp))

            Column(modifier = Modifier.weight(1f)) {
                Text(
                    text = garment.brand,
                    fontFamily = OutfitFont,
                    fontWeight = FontWeight.Bold,
                    fontSize = 11.sp,
                    color = AccentGold
                )
                Text(
                    text = garment.subcategory,
                    fontFamily = PlayfairFont,
                    fontWeight = FontWeight.Medium,
                    fontSize = 16.sp,
                    color = TextLight
                )
                
                Spacer(modifier = Modifier.height(4.dp))

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    Text(
                        text = "CPW: $${garment.costPerWear}",
                        fontFamily = OutfitFont,
                        fontSize = 12.sp,
                        fontWeight = FontWeight.Bold,
                        color = ErrorColor
                    )
                    Text(
                        text = "• Worn ${garment.wearCount}x",
                        fontFamily = OutfitFont,
                        fontSize = 12.sp,
                        color = TextMuted
                    )
                }
            }

            IconButton(onClick = onListClick) {
                Icon(
                    imageVector = Icons.Default.Sell,
                    contentDescription = "List for sale",
                    tint = AccentGold
                )
            }
        }
    }
}
